### ISSUE TITLE
Repassar conteúdo para /AprendaBitcoin e remover esse repo

### ISSUE THREAD

**Issue by paladini** [btcbrdev/oBitcoin#1]
Falando pelo Facebook decidimos que esse repositório seria removido pois o repositório "AprendaBitcoin" já tem a mesma finalidade. 

Quem poderia repassar o conteúdo da Wiki desse repo para o "AprendaBitcoin" e depois excluir esse repositório?

**Comment by felipelalli** [comment]
Não foi esse o combinado, acho que houve um mal entendido. O que eu disse é que podemos usar o "AprendaBitcoin" para iniciar alguma coisa e então aproveitar o conteúdo aqui. Este repositório deve ser mantido pois nele haverá vários projetos relacionados ao /r/oBitcoin, como por exemplo o estilo CSS do subreddit. Além disso, o próprio tópico fixo final deverá ser desenvolvido aqui pois o formato dele provavelmente será distindo do que for feito em "AprendaBitcoin".

**Comment by paladini** [comment]
Entendido então :)
